version: '3.4'

services:
  mysqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    volumes:
      - mysqlservervolume:/var/opt/mssql
      - ${HOME}\.aspnet\https:/https
    environment:
      MSSQL_SA_PASSWORD: "vV5r9tn0M4@"
      ACCEPT_EULA: Y
    networks:
      mynetwork:
        aliases:
          - mysqlserver
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "$${MSSQL_SA_PASSWORD}" -Q "SELECT 1" -b -o /dev/null
      interval: 20s
      timeout: 15s
      retries: 5
      start_period: 60s

  bookcatalog.api:
    build:
      context: .
    depends_on:
      mysqlserver:
        condition: service_healthy
    restart: on-failure
    ports:
      - "5000:80"
      - "5001:443"
    volumes:
      - ${HOME}\.aspnet\https:/https:ro
      - .\doc:/doc:ro
    environment:
      ASPNETCORE_URLS: "https://+:443;http://+:80"
      ASPNETCORE_HTTPS_PORT: 5001
      ASPNETCORE_Kestrel__Certificates__Default__Password: "mypass123"
      ASPNETCORE_ENVIRONMENT: Container
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/httpsDevCert.pfx
    networks:
      mynetwork:
        aliases:
          - bookcatalog.api

  web:
    build:
      context: Bookcatalog.WebReact
    ports:
      - 3000:3000
    depends_on:
      - bookcatalog.api

volumes:
  mysqlservervolume:


networks:
  mynetwork: {}
